### ISSUE TITLE
Did I miss installation instructions?

### ISSUE THREAD

**Issue by TrevorWesterdahl** [potatoqualitee/psu-themes#8]
Have PS Universal. Would like to try this, but I don't seem to see any installation instructions. Looks like examples depend on a Published folder named "assets" and three files in that folder, but where does the functions.ps1 file go? Same with colors.json, init.psm1, nav.json, etc. Where do the actual theme files go? Maybe I just missed install instructions. Thanks.

**Comment by potatoqualitee** [comment]
Hey Trevor -- this repo was mostly as a preview for PSU themes and for Adam to take. These hemes are now included in PSU.  

https://blog.ironmansoftware.com/powershell-universal-themes/
